name: test_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  bloc_concurrency: ^0.3.0
  dio: ^5.9.1

  either_dart: ^1.0.0
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  freezed: ^3.2.4
  freezed_annotation: ^3.1.0
  logger: ^2.6.2
  pretty_dio_logger: ^1.4.0
  very_good_infinite_list: ^0.9.0

dev_dependencies:
  build_runner: ^2.10.5
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.12.0

flutter:
  uses-material-design: true

  assets:
    - .env

fonts:
  - family: SF Pro Text
    fonts:
      - asset: assets/fonts/SFProText.ttf
        weight: 600
